/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module fifo(wr_clk, wr_rst, wr_en, wr_data, wr_ptr, wr_count, wr_ack, overflow, full, almost_full, rd_clk, rd_rst, rd_en, rd_data, rd_ptr, rd_count, rd_valid, underflow, empty, almost_empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire [3:0] _005_;
  wire [3:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire [3:0] _010_;
  wire [3:0] _011_;
  wire [3:0] _012_;
  wire [3:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire [3:0] _022_;
  wire [3:0] _023_;
  wire [3:0] _024_;
  wire [3:0] _025_;
  wire [3:0] _026_;
  wire [3:0] _027_;
  wire [3:0] _028_;
  wire [3:0] _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire [3:0] _038_;
  wire [3:0] _039_;
  wire [3:0] _040_;
  wire [5:0] _041_;
  wire [3:0] _042_;
  wire [3:0] _043_;
  wire [3:0] _044_;
  wire [3:0] _045_;
  wire [3:0] _046_;
  wire [3:0] _047_;
  wire [4:0] _048_;
  output almost_empty;
  wire almost_empty;
  output almost_full;
  wire almost_full;
  wire [3:0] \bin2gray$func$fifo.v:129$7.bin ;
  wire [3:0] \bin2gray$func$fifo.v:130$8.bin ;
  output empty;
  wire empty;
  output full;
  wire full;
  wire [3:0] \gray2bin$func$fifo.v:132$9.gray ;
  wire [31:0] \gray2bin$func$fifo.v:132$9.idx ;
  wire [3:0] \gray2bin$func$fifo.v:133$10.gray ;
  wire [31:0] \gray2bin$func$fifo.v:133$10.idx ;
  wire [3:0] \invert_msb2$func$fifo.v:149$11.gray ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  output overflow;
  wire overflow;
  wire [3:0] rd_bin;
  wire [3:0] rd_bin_next;
  wire [3:0] rd_bin_sync;
  input rd_clk;
  wire rd_clk;
  output [3:0] rd_count;
  wire [3:0] rd_count;
  wire [31:0] rd_count_cmp;
  wire [3:0] rd_count_int;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  input rd_en;
  wire rd_en;
  wire [3:0] rd_gray;
  wire [3:0] rd_gray_next;
  wire [3:0] rd_gray_sync1;
  wire [3:0] rd_gray_sync2;
  wire rd_pop;
  wire [3:0] rd_pop_ext;
  output [2:0] rd_ptr;
  wire [2:0] rd_ptr;
  input rd_rst;
  wire rd_rst;
  wire rd_rst_local;
  wire [1:0] rd_rst_pipe;
  output rd_valid;
  wire rd_valid;
  output underflow;
  wire underflow;
  output wr_ack;
  wire wr_ack;
  wire [3:0] wr_bin;
  wire [3:0] wr_bin_next;
  wire [3:0] wr_bin_sync;
  input wr_clk;
  wire wr_clk;
  output [3:0] wr_count;
  wire [3:0] wr_count;
  wire [31:0] wr_count_cmp;
  wire [3:0] wr_count_int;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  wire [3:0] wr_gray;
  wire [3:0] wr_gray_next;
  wire [3:0] wr_gray_sync1;
  wire [3:0] wr_gray_sync2;
  output [2:0] wr_ptr;
  wire [2:0] wr_ptr;
  wire wr_push;
  wire [3:0] wr_push_ext;
  input wr_rst;
  wire wr_rst;
  wire wr_rst_local;
  wire [1:0] wr_rst_pipe;
  LUT2 #(
    .INIT(4'h6)
  ) _049_ (
    .I0(wr_gray_sync2[2]),
    .I1(wr_gray_sync2[3]),
    .O(wr_bin_sync[2])
  );
  LUT4 #(
    .INIT(16'h6996)
  ) _050_ (
    .I0(wr_gray_sync2[0]),
    .I1(wr_gray_sync2[1]),
    .I2(wr_gray_sync2[2]),
    .I3(wr_gray_sync2[3]),
    .O(wr_bin_sync[0])
  );
  LUT2 #(
    .INIT(4'h6)
  ) _051_ (
    .I0(wr_bin_sync[2]),
    .I1(wr_gray_sync2[1]),
    .O(wr_bin_sync[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _052_ (
    .I0(empty),
    .I1(rd_en),
    .O(rd_pop)
  );
  LUT6 #(
    .INIT(64'h0000000100000000)
  ) _053_ (
    .I0(wr_bin[2]),
    .I1(wr_bin[0]),
    .I2(wr_bin[1]),
    .I3(wr_rst_local),
    .I4(wr_rst),
    .I5(wr_push),
    .O(_021_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _054_ (
    .I0(full),
    .I1(wr_en),
    .O(wr_push)
  );
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _055_ (
    .I0(wr_bin[2]),
    .I1(wr_bin[1]),
    .I2(wr_rst_local),
    .I3(wr_rst),
    .I4(wr_bin[0]),
    .I5(wr_push),
    .O(_020_)
  );
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _056_ (
    .I0(wr_bin[2]),
    .I1(wr_bin[0]),
    .I2(wr_rst_local),
    .I3(wr_rst),
    .I4(wr_push),
    .I5(wr_bin[1]),
    .O(_019_)
  );
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _057_ (
    .I0(wr_bin[2]),
    .I1(wr_rst_local),
    .I2(wr_rst),
    .I3(wr_bin[1]),
    .I4(wr_push),
    .I5(wr_bin[0]),
    .O(_018_)
  );
  LUT6 #(
    .INIT(64'h0001000000000000)
  ) _058_ (
    .I0(wr_bin[0]),
    .I1(wr_bin[1]),
    .I2(wr_rst_local),
    .I3(wr_rst),
    .I4(wr_push),
    .I5(wr_bin[2]),
    .O(_017_)
  );
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _059_ (
    .I0(wr_bin[1]),
    .I1(wr_rst_local),
    .I2(wr_rst),
    .I3(wr_push),
    .I4(wr_bin[2]),
    .I5(wr_bin[0]),
    .O(_016_)
  );
  LUT6 #(
    .INIT(64'h0100000000000000)
  ) _060_ (
    .I0(wr_bin[0]),
    .I1(wr_rst_local),
    .I2(wr_rst),
    .I3(wr_bin[1]),
    .I4(wr_bin[2]),
    .I5(wr_push),
    .O(_015_)
  );
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _061_ (
    .I0(wr_rst_local),
    .I1(wr_rst),
    .I2(wr_bin[0]),
    .I3(wr_bin[1]),
    .I4(wr_push),
    .I5(wr_bin[2]),
    .O(_014_)
  );
  LUT3 #(
    .INIT(8'h40)
  ) _062_ (
    .I0(rd_rst_local),
    .I1(empty),
    .I2(rd_en),
    .O(_008_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _063_ (
    .I0(rd_rst_local),
    .I1(rd_pop),
    .O(_007_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _064_ (
    .I0(rd_rst_local),
    .I1(wr_gray_sync1[0]),
    .O(_013_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _065_ (
    .I0(rd_rst_local),
    .I1(wr_gray_sync1[1]),
    .O(_013_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _066_ (
    .I0(rd_rst_local),
    .I1(wr_gray_sync1[2]),
    .O(_013_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _067_ (
    .I0(rd_rst_local),
    .I1(wr_gray_sync1[3]),
    .O(_013_[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _068_ (
    .I0(rd_rst_local),
    .I1(wr_gray[0]),
    .O(_012_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _069_ (
    .I0(rd_rst_local),
    .I1(wr_gray[1]),
    .O(_012_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _070_ (
    .I0(rd_rst_local),
    .I1(wr_gray[2]),
    .O(_012_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _071_ (
    .I0(rd_rst_local),
    .I1(wr_bin[3]),
    .O(_012_[3])
  );
  LUT3 #(
    .INIT(8'h14)
  ) _072_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[0]),
    .I2(rd_bin_next[1]),
    .O(_004_[0])
  );
  LUT3 #(
    .INIT(8'h14)
  ) _073_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[1]),
    .I2(rd_bin_next[2]),
    .O(_004_[1])
  );
  LUT3 #(
    .INIT(8'h14)
  ) _074_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[3]),
    .I2(rd_bin_next[2]),
    .O(_004_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _075_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[3]),
    .O(_003_[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _076_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[0]),
    .O(_003_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _077_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[1]),
    .O(_003_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _078_ (
    .I0(rd_rst_local),
    .I1(rd_bin_next[2]),
    .O(_003_[2])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _079_ (
    .I0(\mem[6] [0]),
    .I1(\mem[2] [0]),
    .I2(\mem[7] [0]),
    .I3(\mem[3] [0]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_045_[1])
  );
  LUT6 #(
    .INIT(64'h333355550f0f00ff)
  ) _080_ (
    .I0(\mem[4] [0]),
    .I1(\mem[5] [0]),
    .I2(\mem[1] [0]),
    .I3(\mem[0] [0]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_045_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _081_ (
    .I0(\mem[6] [1]),
    .I1(\mem[2] [1]),
    .I2(\mem[7] [1]),
    .I3(\mem[3] [1]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_046_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _082_ (
    .I0(\mem[4] [1]),
    .I1(\mem[0] [1]),
    .I2(\mem[5] [1]),
    .I3(\mem[1] [1]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_046_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _083_ (
    .I0(\mem[6] [2]),
    .I1(\mem[2] [2]),
    .I2(\mem[7] [2]),
    .I3(\mem[3] [2]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_043_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _084_ (
    .I0(\mem[4] [2]),
    .I1(\mem[0] [2]),
    .I2(\mem[5] [2]),
    .I3(\mem[1] [2]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_043_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _085_ (
    .I0(\mem[6] [3]),
    .I1(\mem[2] [3]),
    .I2(\mem[7] [3]),
    .I3(\mem[3] [3]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_042_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _086_ (
    .I0(\mem[4] [3]),
    .I1(\mem[0] [3]),
    .I2(\mem[5] [3]),
    .I3(\mem[1] [3]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_042_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _087_ (
    .I0(\mem[6] [4]),
    .I1(\mem[2] [4]),
    .I2(\mem[7] [4]),
    .I3(\mem[3] [4]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_038_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _088_ (
    .I0(\mem[4] [4]),
    .I1(\mem[0] [4]),
    .I2(\mem[5] [4]),
    .I3(\mem[1] [4]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_038_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _089_ (
    .I0(\mem[6] [5]),
    .I1(\mem[2] [5]),
    .I2(\mem[7] [5]),
    .I3(\mem[3] [5]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_040_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _090_ (
    .I0(\mem[4] [5]),
    .I1(\mem[0] [5]),
    .I2(\mem[5] [5]),
    .I3(\mem[1] [5]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_040_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _091_ (
    .I0(\mem[6] [6]),
    .I1(\mem[2] [6]),
    .I2(\mem[7] [6]),
    .I3(\mem[3] [6]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_039_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _092_ (
    .I0(\mem[4] [6]),
    .I1(\mem[0] [6]),
    .I2(\mem[5] [6]),
    .I3(\mem[1] [6]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_039_[0])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _093_ (
    .I0(\mem[6] [7]),
    .I1(\mem[2] [7]),
    .I2(\mem[7] [7]),
    .I3(\mem[3] [7]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_044_[1])
  );
  LUT6 #(
    .INIT(64'h0f0f555500ff3333)
  ) _094_ (
    .I0(\mem[4] [7]),
    .I1(\mem[0] [7]),
    .I2(\mem[5] [7]),
    .I3(\mem[1] [7]),
    .I4(rd_bin[0]),
    .I5(rd_bin[2]),
    .O(_044_[0])
  );
  LUT6 #(
    .INIT(64'h0110044000000000)
  ) _095_ (
    .I0(wr_rst_local),
    .I1(_041_[1]),
    .I2(_041_[2]),
    .I3(rd_gray_sync2[0]),
    .I4(rd_gray_sync2[1]),
    .I5(_041_[5]),
    .O(_001_)
  );
  LUT2 #(
    .INIT(4'h9)
  ) _096_ (
    .I0(wr_bin_next[1]),
    .I1(wr_bin_next[2]),
    .O(_041_[1])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _097_ (
    .I0(wr_bin_next[0]),
    .I1(wr_bin_next[1]),
    .O(_041_[2])
  );
  LUT4 #(
    .INIT(16'h2148)
  ) _098_ (
    .I0(rd_gray_sync2[2]),
    .I1(rd_gray_sync2[3]),
    .I2(wr_bin_next[2]),
    .I3(wr_bin_next[3]),
    .O(_041_[5])
  );
  LUT3 #(
    .INIT(8'h40)
  ) _099_ (
    .I0(wr_rst_local),
    .I1(wr_en),
    .I2(full),
    .O(_002_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _100_ (
    .I0(wr_rst_local),
    .I1(wr_push),
    .O(_009_)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _101_ (
    .I0(wr_rst_local),
    .I1(rd_gray_sync1[0]),
    .O(_006_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _102_ (
    .I0(wr_rst_local),
    .I1(rd_gray_sync1[1]),
    .O(_006_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _103_ (
    .I0(wr_rst_local),
    .I1(rd_gray_sync1[2]),
    .O(_006_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _104_ (
    .I0(wr_rst_local),
    .I1(rd_gray_sync1[3]),
    .O(_006_[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _105_ (
    .I0(wr_rst_local),
    .I1(rd_gray[0]),
    .O(_005_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _106_ (
    .I0(wr_rst_local),
    .I1(rd_gray[1]),
    .O(_005_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _107_ (
    .I0(wr_rst_local),
    .I1(rd_gray[2]),
    .O(_005_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _108_ (
    .I0(wr_rst_local),
    .I1(rd_bin[3]),
    .O(_005_[3])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _109_ (
    .I0(_041_[2]),
    .I1(wr_rst_local),
    .O(_011_[0])
  );
  LUT2 #(
    .INIT(4'h1)
  ) _110_ (
    .I0(_041_[1]),
    .I1(wr_rst_local),
    .O(_011_[1])
  );
  LUT3 #(
    .INIT(8'h14)
  ) _111_ (
    .I0(wr_rst_local),
    .I1(wr_bin_next[3]),
    .I2(wr_bin_next[2]),
    .O(_011_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _112_ (
    .I0(wr_rst_local),
    .I1(wr_bin_next[3]),
    .O(_010_[3])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _113_ (
    .I0(wr_rst_local),
    .I1(wr_bin_next[0]),
    .O(_010_[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _114_ (
    .I0(wr_rst_local),
    .I1(wr_bin_next[1]),
    .O(_010_[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _115_ (
    .I0(wr_rst_local),
    .I1(wr_bin_next[2]),
    .O(_010_[2])
  );
  LUT5 #(
    .INIT(32'd3203115690)
  ) _116_ (
    .I0(rd_rst_local),
    .I1(wr_gray_sync2[0]),
    .I2(rd_bin_next[0]),
    .I3(rd_bin_next[1]),
    .I4(_048_[4]),
    .O(_000_)
  );
  LUT6 #(
    .INIT(64'h1004800220084001)
  ) _117_ (
    .I0(wr_gray_sync2[1]),
    .I1(wr_gray_sync2[2]),
    .I2(wr_gray_sync2[3]),
    .I3(rd_bin_next[3]),
    .I4(rd_bin_next[2]),
    .I5(rd_bin_next[1]),
    .O(_048_[4])
  );
  LUT4 #(
    .INIT(16'h6996)
  ) _118_ (
    .I0(_047_[0]),
    .I1(rd_gray_sync2[0]),
    .I2(rd_gray_sync2[1]),
    .I3(wr_bin[0]),
    .O(_027_[0])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _119_ (
    .I0(rd_gray_sync2[2]),
    .I1(rd_gray_sync2[3]),
    .O(_047_[0])
  );
  LUT3 #(
    .INIT(8'h96)
  ) _120_ (
    .I0(_047_[0]),
    .I1(rd_gray_sync2[1]),
    .I2(wr_bin[1]),
    .O(_027_[1])
  );
  LUT2 #(
    .INIT(4'h6)
  ) _121_ (
    .I0(_047_[0]),
    .I1(wr_bin[2]),
    .O(_027_[2])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _122_ (
    .I0(rd_gray_sync2[3]),
    .I1(wr_bin[3]),
    .O(_027_[3])
  );
  LUT2 #(
    .INIT(4'h6)
  ) _123_ (
    .I0(wr_push),
    .I1(wr_bin[0]),
    .O(_025_[0])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _124_ (
    .I0(wr_bin_sync[0]),
    .I1(rd_bin[0]),
    .O(_029_[0])
  );
  LUT3 #(
    .INIT(8'h69)
  ) _125_ (
    .I0(wr_bin_sync[2]),
    .I1(wr_gray_sync2[1]),
    .I2(rd_bin[1]),
    .O(_029_[1])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _126_ (
    .I0(wr_bin_sync[2]),
    .I1(rd_bin[2]),
    .O(_029_[2])
  );
  LUT2 #(
    .INIT(4'h9)
  ) _127_ (
    .I0(wr_gray_sync2[3]),
    .I1(rd_bin[3]),
    .O(_029_[3])
  );
  LUT2 #(
    .INIT(4'h6)
  ) _128_ (
    .I0(rd_pop),
    .I1(rd_bin[0]),
    .O(_023_[0])
  );
  LUT4 #(
    .INIT(16'hff80)
  ) _129_ (
    .I0(wr_count[0]),
    .I1(wr_count[1]),
    .I2(wr_count[2]),
    .I3(wr_count[3]),
    .O(almost_full)
  );
  LUT3 #(
    .INIT(8'h01)
  ) _130_ (
    .I0(rd_count[2]),
    .I1(rd_count[3]),
    .I2(rd_count[1]),
    .O(almost_empty)
  );
  CARRY4 _131_ (
    .CI(1'h0),
    .CO(_022_),
    .CYINIT(1'h0),
    .DI({ 3'h0, rd_pop }),
    .O(rd_bin_next),
    .S({ rd_bin[3:1], _023_[0] })
  );
  CARRY4 _132_ (
    .CI(1'h0),
    .CO(_024_),
    .CYINIT(1'h0),
    .DI({ 3'h0, wr_push }),
    .O(wr_bin_next),
    .S({ wr_bin[3:1], _025_[0] })
  );
  CARRY4 _133_ (
    .CI(1'h0),
    .CO(_026_),
    .CYINIT(1'h1),
    .DI(wr_bin),
    .O(wr_count),
    .S(_027_)
  );
  CARRY4 _134_ (
    .CI(1'h0),
    .CO(_028_),
    .CYINIT(1'h1),
    .DI({ wr_gray_sync2[3], wr_bin_sync[2:0] }),
    .O(rd_count),
    .S(_029_)
  );
  FDRE #(
    .INIT(1'hx)
  ) _135_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[0]),
    .Q(\mem[7] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _136_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[1]),
    .Q(\mem[7] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _137_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[2]),
    .Q(\mem[7] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _138_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[3]),
    .Q(\mem[7] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _139_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[4]),
    .Q(\mem[7] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _140_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[5]),
    .Q(\mem[7] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _141_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[6]),
    .Q(\mem[7] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _142_ (
    .C(wr_clk),
    .CE(_014_),
    .D(wr_data[7]),
    .Q(\mem[7] [7]),
    .R(1'h0)
  );
  FDCE #(
    .INIT(1'hx)
  ) _143_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_007_),
    .Q(rd_valid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _144_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_008_),
    .Q(underflow)
  );
  FDPE #(
    .INIT(1'hx)
  ) _145_ (
    .C(rd_clk),
    .CE(1'h1),
    .D(_000_),
    .PRE(rd_rst),
    .Q(empty)
  );
  FDCE #(
    .INIT(1'hx)
  ) _146_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_003_[0]),
    .Q(rd_bin[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _147_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_003_[1]),
    .Q(rd_bin[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _148_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_003_[2]),
    .Q(rd_bin[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _149_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_003_[3]),
    .Q(rd_bin[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _150_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_004_[0]),
    .Q(rd_gray[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _151_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_004_[1]),
    .Q(rd_gray[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _152_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_004_[2]),
    .Q(rd_gray[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _153_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_012_[0]),
    .Q(wr_gray_sync1[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _154_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_012_[1]),
    .Q(wr_gray_sync1[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _155_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_012_[2]),
    .Q(wr_gray_sync1[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _156_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_012_[3]),
    .Q(wr_gray_sync1[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _157_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_013_[0]),
    .Q(wr_gray_sync2[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _158_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_013_[1]),
    .Q(wr_gray_sync2[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _159_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_013_[2]),
    .Q(wr_gray_sync2[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _160_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_013_[3]),
    .Q(wr_gray_sync2[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _161_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_009_),
    .Q(wr_ack)
  );
  FDCE #(
    .INIT(1'hx)
  ) _162_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_002_),
    .Q(overflow)
  );
  FDCE #(
    .INIT(1'hx)
  ) _163_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_001_),
    .Q(full)
  );
  FDCE #(
    .INIT(1'hx)
  ) _164_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_010_[0]),
    .Q(wr_bin[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _165_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_010_[1]),
    .Q(wr_bin[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _166_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_010_[2]),
    .Q(wr_bin[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _167_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_010_[3]),
    .Q(wr_bin[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _168_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_011_[0]),
    .Q(wr_gray[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _169_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_011_[1]),
    .Q(wr_gray[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _170_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_011_[2]),
    .Q(wr_gray[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _171_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_005_[0]),
    .Q(rd_gray_sync1[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _172_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_005_[1]),
    .Q(rd_gray_sync1[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _173_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_005_[2]),
    .Q(rd_gray_sync1[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _174_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_005_[3]),
    .Q(rd_gray_sync1[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _175_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_006_[0]),
    .Q(rd_gray_sync2[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _176_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_006_[1]),
    .Q(rd_gray_sync2[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _177_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_006_[2]),
    .Q(rd_gray_sync2[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _178_ (
    .C(wr_clk),
    .CE(1'h1),
    .CLR(wr_rst),
    .D(_006_[3]),
    .Q(rd_gray_sync2[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _179_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_036_),
    .Q(rd_data[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _180_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_030_),
    .Q(rd_data[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _181_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_031_),
    .Q(rd_data[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _182_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_032_),
    .Q(rd_data[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _183_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_033_),
    .Q(rd_data[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _184_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_034_),
    .Q(rd_data[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _185_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_035_),
    .Q(rd_data[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _186_ (
    .C(rd_clk),
    .CE(1'h1),
    .CLR(rd_rst),
    .D(_037_),
    .Q(rd_data[7])
  );
  FDRE #(
    .INIT(1'hx)
  ) _187_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[0]),
    .Q(\mem[0] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _188_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[1]),
    .Q(\mem[0] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _189_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[2]),
    .Q(\mem[0] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _190_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[3]),
    .Q(\mem[0] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _191_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[4]),
    .Q(\mem[0] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _192_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[5]),
    .Q(\mem[0] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _193_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[6]),
    .Q(\mem[0] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _194_ (
    .C(wr_clk),
    .CE(_021_),
    .D(wr_data[7]),
    .Q(\mem[0] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _195_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[0]),
    .Q(\mem[1] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _196_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[1]),
    .Q(\mem[1] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _197_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[2]),
    .Q(\mem[1] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _198_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[3]),
    .Q(\mem[1] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _199_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[4]),
    .Q(\mem[1] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _200_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[5]),
    .Q(\mem[1] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _201_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[6]),
    .Q(\mem[1] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _202_ (
    .C(wr_clk),
    .CE(_020_),
    .D(wr_data[7]),
    .Q(\mem[1] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _203_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[0]),
    .Q(\mem[2] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _204_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[1]),
    .Q(\mem[2] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _205_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[2]),
    .Q(\mem[2] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _206_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[3]),
    .Q(\mem[2] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _207_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[4]),
    .Q(\mem[2] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _208_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[5]),
    .Q(\mem[2] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _209_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[6]),
    .Q(\mem[2] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _210_ (
    .C(wr_clk),
    .CE(_019_),
    .D(wr_data[7]),
    .Q(\mem[2] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _211_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[0]),
    .Q(\mem[3] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _212_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[1]),
    .Q(\mem[3] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _213_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[2]),
    .Q(\mem[3] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _214_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[3]),
    .Q(\mem[3] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _215_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[4]),
    .Q(\mem[3] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _216_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[5]),
    .Q(\mem[3] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _217_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[6]),
    .Q(\mem[3] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _218_ (
    .C(wr_clk),
    .CE(_018_),
    .D(wr_data[7]),
    .Q(\mem[3] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _219_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[0]),
    .Q(\mem[4] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _220_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[1]),
    .Q(\mem[4] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _221_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[2]),
    .Q(\mem[4] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _222_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[3]),
    .Q(\mem[4] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _223_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[4]),
    .Q(\mem[4] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _224_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[5]),
    .Q(\mem[4] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _225_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[6]),
    .Q(\mem[4] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _226_ (
    .C(wr_clk),
    .CE(_017_),
    .D(wr_data[7]),
    .Q(\mem[4] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _227_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[0]),
    .Q(\mem[5] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _228_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[1]),
    .Q(\mem[5] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _229_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[2]),
    .Q(\mem[5] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _230_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[3]),
    .Q(\mem[5] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _231_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[4]),
    .Q(\mem[5] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _232_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[5]),
    .Q(\mem[5] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _233_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[6]),
    .Q(\mem[5] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _234_ (
    .C(wr_clk),
    .CE(_016_),
    .D(wr_data[7]),
    .Q(\mem[5] [7]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _235_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[0]),
    .Q(\mem[6] [0]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _236_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[1]),
    .Q(\mem[6] [1]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _237_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[2]),
    .Q(\mem[6] [2]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _238_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[3]),
    .Q(\mem[6] [3]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _239_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[4]),
    .Q(\mem[6] [4]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _240_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[5]),
    .Q(\mem[6] [5]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _241_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[6]),
    .Q(\mem[6] [6]),
    .R(1'h0)
  );
  FDRE #(
    .INIT(1'hx)
  ) _242_ (
    .C(wr_clk),
    .CE(_015_),
    .D(wr_data[7]),
    .Q(\mem[6] [7]),
    .R(1'h0)
  );
  FDPE #(
    .INIT(1'hx)
  ) _243_ (
    .C(rd_clk),
    .CE(1'h1),
    .D(rd_rst_pipe[1]),
    .PRE(rd_rst),
    .Q(rd_rst_local)
  );
  FDPE #(
    .INIT(1'hx)
  ) _244_ (
    .C(rd_clk),
    .CE(1'h1),
    .D(1'h0),
    .PRE(rd_rst),
    .Q(rd_rst_pipe[1])
  );
  FDPE #(
    .INIT(1'hx)
  ) _245_ (
    .C(wr_clk),
    .CE(1'h1),
    .D(wr_rst_pipe[1]),
    .PRE(wr_rst),
    .Q(wr_rst_local)
  );
  FDPE #(
    .INIT(1'hx)
  ) _246_ (
    .C(wr_clk),
    .CE(1'h1),
    .D(1'h0),
    .PRE(wr_rst),
    .Q(wr_rst_pipe[1])
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _247_ (
    .I0(rd_data[1]),
    .I1(rd_pop),
    .I2(_046_[0]),
    .I3(_046_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_030_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _248_ (
    .I0(rd_data[2]),
    .I1(rd_pop),
    .I2(_043_[0]),
    .I3(_043_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_031_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _249_ (
    .I0(rd_data[3]),
    .I1(rd_pop),
    .I2(_042_[0]),
    .I3(_042_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_032_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _250_ (
    .I0(rd_data[4]),
    .I1(rd_pop),
    .I2(_038_[0]),
    .I3(_038_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_033_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _251_ (
    .I0(rd_data[5]),
    .I1(rd_pop),
    .I2(_040_[0]),
    .I3(_040_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_034_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _252_ (
    .I0(rd_data[6]),
    .I1(rd_pop),
    .I2(_039_[0]),
    .I3(_039_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_035_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _253_ (
    .I0(rd_data[0]),
    .I1(rd_pop),
    .I2(_045_[0]),
    .I3(_045_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_036_)
  );
  LUT6 #(
    .INIT(64'h000022ee00002e2e)
  ) _254_ (
    .I0(rd_data[7]),
    .I1(rd_pop),
    .I2(_044_[0]),
    .I3(_044_[1]),
    .I4(rd_rst_local),
    .I5(rd_bin[1]),
    .O(_037_)
  );
  assign _048_[3:0] = { rd_bin_next[1:0], wr_gray_sync2[0], rd_rst_local };
  assign _004_[3] = _003_[3];
  assign _011_[3] = _010_[3];
  assign _038_[3:2] = { rd_bin[1], rd_rst_local };
  assign _043_[3:2] = { rd_bin[1], rd_rst_local };
  assign _040_[3:2] = { rd_bin[1], rd_rst_local };
  assign _042_[3:2] = { rd_bin[1], rd_rst_local };
  assign { _041_[4:3], _041_[0] } = { rd_gray_sync2[1:0], wr_rst_local };
  assign _044_[3:2] = { rd_bin[1], rd_rst_local };
  assign _045_[3:2] = { rd_bin[1], rd_rst_local };
  assign _039_[3:2] = { rd_bin[1], rd_rst_local };
  assign _047_[3:1] = { wr_bin[0], rd_gray_sync2[1:0] };
  assign _046_[3:2] = { rd_bin[1], rd_rst_local };
  assign _023_[3:1] = rd_bin[3:1];
  assign _025_[3:1] = wr_bin[3:1];
  assign \bin2gray$func$fifo.v:129$7.bin  = 4'hx;
  assign \bin2gray$func$fifo.v:130$8.bin  = 4'hx;
  assign \gray2bin$func$fifo.v:132$9.gray  = 4'hx;
  assign \gray2bin$func$fifo.v:132$9.idx  = 32'hxxxxxxxx;
  assign \gray2bin$func$fifo.v:133$10.gray  = 4'hx;
  assign \gray2bin$func$fifo.v:133$10.idx  = 32'hxxxxxxxx;
  assign \invert_msb2$func$fifo.v:149$11.gray  = 4'hx;
  assign rd_bin_sync[3] = rd_gray_sync2[3];
  assign rd_count_cmp = { 28'h0000000, rd_count };
  assign rd_count_int = rd_count;
  assign rd_gray[3] = rd_bin[3];
  assign rd_gray_next[3] = rd_bin_next[3];
  assign rd_pop_ext = { 3'h0, rd_pop };
  assign rd_ptr = rd_bin[2:0];
  assign rd_rst_pipe[0] = rd_rst_local;
  assign wr_bin_sync[3] = wr_gray_sync2[3];
  assign wr_count_cmp = { 28'h0000000, wr_count };
  assign wr_count_int = wr_count;
  assign wr_gray[3] = wr_bin[3];
  assign wr_gray_next[3] = wr_bin_next[3];
  assign wr_ptr = wr_bin[2:0];
  assign wr_push_ext = { 3'h0, wr_push };
  assign wr_rst_pipe[0] = wr_rst_local;
endmodule
