/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module fifo(wr_clk, wr_rst, wr_en, wr_data, wr_ptr, wr_count, wr_ack, overflow, full, almost_full, rd_clk, rd_rst, rd_en, rd_data, rd_ptr, rd_count, rd_valid, underflow, empty, almost_empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire [3:0] _003_;
  wire [7:0] _004_;
  wire [3:0] _005_;
  wire [3:0] _006_;
  wire [3:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [3:0] _011_;
  wire [3:0] _012_;
  wire [3:0] _013_;
  wire [3:0] _014_;
  wire [7:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire [7:0] _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  output almost_empty;
  wire almost_empty;
  output almost_full;
  wire almost_full;
  wire [3:0] \bin2gray$func$fifo.v:129$2.$result ;
  wire [3:0] \bin2gray$func$fifo.v:129$7.bin ;
  wire [3:0] \bin2gray$func$fifo.v:130$3.$result ;
  wire [3:0] \bin2gray$func$fifo.v:130$8.bin ;
  output empty;
  reg empty;
  wire empty_next;
  output full;
  reg full;
  wire full_next;
  wire [3:0] \gray2bin$func$fifo.v:132$9.gray ;
  wire [31:0] \gray2bin$func$fifo.v:132$9.idx ;
  wire [3:0] \gray2bin$func$fifo.v:133$10.gray ;
  wire [31:0] \gray2bin$func$fifo.v:133$10.idx ;
  wire [3:0] \invert_msb2$func$fifo.v:149$11.gray ;
  wire [3:0] \invert_msb2$func$fifo.v:149$6.$result ;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  output overflow;
  reg overflow;
  reg [3:0] rd_bin;
  wire [3:0] rd_bin_next;
  wire [3:0] rd_bin_sync;
  input rd_clk;
  wire rd_clk;
  output [3:0] rd_count;
  wire [3:0] rd_count;
  wire [31:0] rd_count_cmp;
  wire [3:0] rd_count_int;
  output [7:0] rd_data;
  reg [7:0] rd_data;
  input rd_en;
  wire rd_en;
  reg [3:0] rd_gray;
  wire [3:0] rd_gray_next;
  reg [3:0] rd_gray_sync1;
  reg [3:0] rd_gray_sync2;
  wire rd_pop;
  wire [3:0] rd_pop_ext;
  output [2:0] rd_ptr;
  wire [2:0] rd_ptr;
  input rd_rst;
  wire rd_rst;
  wire rd_rst_local;
  reg [1:0] rd_rst_pipe;
  output rd_valid;
  reg rd_valid;
  output underflow;
  reg underflow;
  output wr_ack;
  reg wr_ack;
  reg [3:0] wr_bin;
  wire [3:0] wr_bin_next;
  wire [3:0] wr_bin_sync;
  input wr_clk;
  wire wr_clk;
  output [3:0] wr_count;
  wire [3:0] wr_count;
  wire [31:0] wr_count_cmp;
  wire [3:0] wr_count_int;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  reg [3:0] wr_gray;
  wire [3:0] wr_gray_next;
  reg [3:0] wr_gray_sync1;
  reg [3:0] wr_gray_sync2;
  output [2:0] wr_ptr;
  wire [2:0] wr_ptr;
  wire wr_push;
  wire [3:0] wr_push_ext;
  input wr_rst;
  wire wr_rst;
  wire wr_rst_local;
  reg [1:0] wr_rst_pipe;
  assign wr_bin_next = wr_bin + { 3'h0, wr_push };
  assign rd_bin_next = rd_bin + { 3'h0, rd_pop };
  always @(posedge wr_clk)
    if (_017_) \mem[7]  <= wr_data;
  always @(posedge wr_clk)
    if (_018_) \mem[0]  <= wr_data;
  always @(posedge wr_clk)
    if (_019_) \mem[4]  <= wr_data;
  always @(posedge wr_clk)
    if (_020_) \mem[3]  <= wr_data;
  always @(posedge wr_clk)
    if (_021_) \mem[2]  <= wr_data;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) rd_data <= 8'h00;
    else if (_016_) rd_data <= _004_;
  always @(posedge wr_clk)
    if (_022_) \mem[6]  <= wr_data;
  always @(posedge wr_clk)
    if (_023_) \mem[1]  <= wr_data;
  always @(posedge wr_clk)
    if (_024_) \mem[5]  <= wr_data;
  assign _016_ = | { rd_pop, rd_rst_pipe[0] };
  assign _025_ = ~ wr_rst_pipe[0];
  assign _026_ = ~ wr_rst;
  assign _017_ = & { _036_, _026_, _025_, wr_push };
  assign _018_ = & { _043_, _026_, _025_, wr_push };
  assign _019_ = & { _039_, _026_, _025_, wr_push };
  assign _020_ = & { _040_, _026_, _025_, wr_push };
  assign _021_ = & { _041_, _026_, _025_, wr_push };
  assign _022_ = & { _037_, _026_, _025_, wr_push };
  assign _023_ = & { _042_, _026_, _025_, wr_push };
  assign _024_ = & { _038_, _026_, _025_, wr_push };
  assign full_next = \bin2gray$func$fifo.v:129$2.$result  == { \invert_msb2$func$fifo.v:149$6.$result [3:2], rd_gray_sync2[1:0] };
  assign empty_next = \bin2gray$func$fifo.v:130$3.$result  == wr_gray_sync2;
  assign almost_full = { 28'h0000000, wr_count } >= 32'd7;
  assign almost_empty = { 28'h0000000, rd_count } <= 32'd1;
  assign wr_push = wr_en && _029_;
  assign rd_pop = rd_en && _030_;
  assign _027_ = wr_en && full;
  assign _028_ = rd_en && empty;
  assign _029_ = ! full;
  assign _030_ = ! empty;
  assign \invert_msb2$func$fifo.v:149$6.$result [3] = ~ rd_gray_sync2[3];
  assign \invert_msb2$func$fifo.v:149$6.$result [2] = ~ rd_gray_sync2[2];
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) rd_valid <= 1'h0;
    else rd_valid <= _008_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) underflow <= 1'h0;
    else underflow <= _009_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) empty <= 1'h1;
    else empty <= _000_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) rd_bin <= 4'h0;
    else rd_bin <= _003_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) rd_gray <= 4'h0;
    else rd_gray <= _005_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) wr_gray_sync1 <= 4'h0;
    else wr_gray_sync1 <= _013_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) wr_gray_sync2 <= 4'h0;
    else wr_gray_sync2 <= _014_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) wr_ack <= 1'h0;
    else wr_ack <= _010_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) overflow <= 1'h0;
    else overflow <= _002_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) full <= 1'h0;
    else full <= _001_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) wr_bin <= 4'h0;
    else wr_bin <= _011_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) wr_gray <= 4'h0;
    else wr_gray <= _012_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) rd_gray_sync1 <= 4'h0;
    else rd_gray_sync1 <= _006_;
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) rd_gray_sync2 <= 4'h0;
    else rd_gray_sync2 <= _007_;
  always @(posedge rd_clk, posedge rd_rst)
    if (rd_rst) rd_rst_pipe <= 2'h3;
    else rd_rst_pipe <= { 1'h0, rd_rst_pipe[1] };
  always @(posedge wr_clk, posedge wr_rst)
    if (wr_rst) wr_rst_pipe <= 2'h3;
    else wr_rst_pipe <= { 1'h0, wr_rst_pipe[1] };
  assign _031_ = rd_bin[2:0] == 3'h3;
  assign _032_ = rd_bin[2:0] == 3'h2;
  assign _033_ = rd_bin[2:0] == 3'h1;
  assign _034_ = ! rd_bin[2:0];
  assign _000_ = rd_rst_pipe[0] ? 1'h1 : empty_next;
  assign _009_ = rd_rst_pipe[0] ? 1'h0 : _028_;
  assign _008_ = rd_rst_pipe[0] ? 1'h0 : rd_pop;
  assign _014_ = rd_rst_pipe[0] ? 4'h0 : wr_gray_sync1;
  assign _013_ = rd_rst_pipe[0] ? 4'h0 : wr_gray;
  assign _005_ = rd_rst_pipe[0] ? 4'h0 : \bin2gray$func$fifo.v:130$3.$result ;
  assign _003_ = rd_rst_pipe[0] ? 4'h0 : rd_bin_next;
  assign _035_ = rd_pop ? _015_ : 8'hxx;
  assign _004_ = rd_rst_pipe[0] ? 8'h00 : _035_;
  assign _001_ = wr_rst_pipe[0] ? 1'h0 : full_next;
  assign _002_ = wr_rst_pipe[0] ? 1'h0 : _027_;
  assign _010_ = wr_rst_pipe[0] ? 1'h0 : wr_push;
  assign _007_ = wr_rst_pipe[0] ? 4'h0 : rd_gray_sync1;
  assign _006_ = wr_rst_pipe[0] ? 4'h0 : rd_gray;
  assign _012_ = wr_rst_pipe[0] ? 4'h0 : \bin2gray$func$fifo.v:129$2.$result ;
  assign _011_ = wr_rst_pipe[0] ? 4'h0 : wr_bin_next;
  assign _036_ = wr_bin[2:0] == 3'h7;
  assign _037_ = wr_bin[2:0] == 3'h6;
  assign _038_ = wr_bin[2:0] == 3'h5;
  assign _039_ = wr_bin[2:0] == 3'h4;
  assign _040_ = wr_bin[2:0] == 3'h3;
  assign _041_ = wr_bin[2:0] == 3'h2;
  assign _042_ = wr_bin[2:0] == 3'h1;
  assign _043_ = ! wr_bin[2:0];
  function [7:0] _126_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _126_ = b[7:0];
      8'b??????1?:
        _126_ = b[15:8];
      8'b?????1??:
        _126_ = b[23:16];
      8'b????1???:
        _126_ = b[31:24];
      8'b???1????:
        _126_ = b[39:32];
      8'b??1?????:
        _126_ = b[47:40];
      8'b?1??????:
        _126_ = b[55:48];
      8'b1???????:
        _126_ = b[63:56];
      default:
        _126_ = a;
    endcase
  endfunction
  assign _015_ = _126_(8'hxx, { \mem[0] , \mem[1] , \mem[2] , \mem[3] , \mem[4] , \mem[5] , \mem[6] , \mem[7]  }, { _034_, _033_, _032_, _031_, _047_, _046_, _045_, _044_ });
  assign _044_ = rd_bin[2:0] == 3'h7;
  assign _045_ = rd_bin[2:0] == 3'h6;
  assign _046_ = rd_bin[2:0] == 3'h5;
  assign _047_ = rd_bin[2:0] == 3'h4;
  assign rd_bin_sync[0] = ^ rd_gray_sync2;
  assign rd_bin_sync[1] = ^ { 1'h0, rd_gray_sync2[3:1] };
  assign rd_bin_sync[2] = ^ { 2'h0, rd_gray_sync2[3:2] };
  assign rd_bin_sync[3] = ^ { 3'h0, rd_gray_sync2[3] };
  assign wr_bin_sync[0] = ^ wr_gray_sync2;
  assign wr_bin_sync[1] = ^ { 1'h0, wr_gray_sync2[3:1] };
  assign wr_bin_sync[2] = ^ { 2'h0, wr_gray_sync2[3:2] };
  assign wr_bin_sync[3] = ^ { 3'h0, wr_gray_sync2[3] };
  assign wr_count = wr_bin - rd_bin_sync;
  assign rd_count = wr_bin_sync - rd_bin;
  assign \bin2gray$func$fifo.v:129$2.$result  = { 1'h0, wr_bin_next[3:1] } ^ wr_bin_next;
  assign \bin2gray$func$fifo.v:130$3.$result  = { 1'h0, rd_bin_next[3:1] } ^ rd_bin_next;
  assign \bin2gray$func$fifo.v:129$7.bin  = 4'hx;
  assign \bin2gray$func$fifo.v:130$8.bin  = 4'hx;
  assign \gray2bin$func$fifo.v:132$9.gray  = 4'hx;
  assign \gray2bin$func$fifo.v:132$9.idx  = 32'hxxxxxxxx;
  assign \gray2bin$func$fifo.v:133$10.gray  = 4'hx;
  assign \gray2bin$func$fifo.v:133$10.idx  = 32'hxxxxxxxx;
  assign \invert_msb2$func$fifo.v:149$11.gray  = 4'hx;
  assign \invert_msb2$func$fifo.v:149$6.$result [1:0] = rd_gray_sync2[1:0];
  assign rd_count_cmp = { 28'h0000000, rd_count };
  assign rd_count_int = rd_count;
  assign rd_gray_next = \bin2gray$func$fifo.v:130$3.$result ;
  assign rd_pop_ext = { 3'h0, rd_pop };
  assign rd_ptr = rd_bin[2:0];
  assign rd_rst_local = rd_rst_pipe[0];
  assign wr_count_cmp = { 28'h0000000, wr_count };
  assign wr_count_int = wr_count;
  assign wr_gray_next = \bin2gray$func$fifo.v:129$2.$result ;
  assign wr_ptr = wr_bin[2:0];
  assign wr_push_ext = { 3'h0, wr_push };
  assign wr_rst_local = wr_rst_pipe[0];
endmodule
